sample_rate: 22050
n_mel_channels: 80
n_window_size: 1024
n_window_stride: 256
n_fft: 1024

# "vits" or "fastpitch_hifigan"
model_choice: "vits" 

# Load method is either "pretrained" or "checkpoint"
# Checkpoint path example: "/path/to/model.nemo"

vits_config:
  load_method: "pretrained"
  pretrained_model: "tts_en_vits" 
  checkpoint_path: null

components_config:
  generator:
    load_method: "pretrained"
    pretrained_model: "tts_en_fastpitch"
    checkpoint_path: null
  vocoder:
    load_method: "pretrained"
    pretrained_model: "tts_en_hifigan"
    checkpoint_path: null
    