sample_rate: 22050
n_mel_channels: 80
n_window_size: 1024
n_window_stride: 256
n_fft: 1024

dataset:
  data_name: "tts_sunda"
  repo_id: "syarief-mulyadi/pbl-tts-dataset"
  filename: "sundanese/su_id_male_01596.zip"
  variant: "sundanese"  # "sundanese" (zip) or "indonesian" (tgz Librivox)
  transcript_filename: "line_index.tsv"
  metadata_filename: null
  language: null
  split_subdir: "test"
  extracted_subdir: null
  split:
    train_size: null
    eval_size: 10
    seed: 42

# "vits" or "fastpitch_hifigan"
model_choice: "vits" 

# Load method is either "pretrained" or "checkpoint"
# Checkpoint path example: "/path/to/model.nemo"

vits_config:
  load_method: "pretrained"
  pretrained_model: "tts_en_lj_vits" 
  checkpoint_path: null

components_config:
  generator:
    load_method: "pretrained"
    pretrained_model: "tts_en_fastpitch"
    checkpoint_path: null
  vocoder:
    load_method: "pretrained"
    pretrained_model: "tts_en_hifigan"
    checkpoint_path: null
    